id: P44C5EAA4
initial_creation_type: input
source_metadata:
  title: Thirteenth Dalai Lama Series
  language: fr
  description: 'Texts by the Great Thirteenth Dalai Lama Tupten Gyatso (thub bstan
    rgya mtsho, 1876–1933):'
  volume:
    2686fbb74d064dc1a12812728f0fbca5:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Sādhanas
    50c26264920746ae93b32e30087eee1c:
      title: 'The Tambura of Devotion: A Prayer for the Swift Appearance of the Supreme
        Tulku of the All-Seeing Conqueror and Cardinal Guardian of the Land of Snows'
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:48:11.981858'
last_modified_at: '2022-03-01T01:48:11.981861'
